### ISSUE TITLE
Authentication fails when jwt server is updated

### ISSUE THREAD

**Issue by TahaMunir1** [curityio/flask-of-oil#11]
I have followed the implementation and configured with jwt. It works fine until there is a change in the deployment of jwt server. It keeps on returning 401 error. When the service is restarted, a new _auth variable is created and then it starts working fine. Any fix for this?

**Comment by mtrojanowski** [comment]
Hey @TahaMunir1, can you please give a bit more details of the problem?

1. What changes in the JWT server are you referring to? Do the signing keys change? Is there any change in the URL, etc?
2. Can you enable debug logging and check what is the concrete error from the library? What exactly causes the rejection of the token.
3. Are you using opaque tokens or JWTs? Can you show how are you configuring the filter?

I tried to reproduce the problem, but so far couldn't. I used JWT tokens and passed a jwks_uri to the filter. In fact, the filter caches the response from the JWKS URI, so I was able to verify tokens even when I switched off my Authorization Server completely.

I'm sure we'll be able to find a solution.

**Comment by mtrojanowski** [comment]
I drilled a bit more and managed to find the problem. The key set is only fetched once when the validator is created. In #14 I added refreshing of the key set when no suitable key is found. This should resolve the problem.

**Comment by mtrojanowski** [comment]
@TahaMunir1 The fix is now merged and released in version 1.2.0. The library will now try to fetch new keys from the JWKS endpoint if the library returns an error that no suitable key was found in memory. The fetching of new keys will only be performed after 30 seconds passed from the previous successful fetch.
