### ISSUE TITLE
Support multiple validators for various issuers

### ISSUE THREAD

**Issue by travisspencer** [curityio/flask-of-oil#2]
It should be easily possible to configure support for multiple issuers (i.e., OAuth servers). A token validator should be created for each configured issuer. When an access token is presented to an API, the filter should determine the issuer of that token, and use the appropriate validator. Because this is not possible for opaque tokens, it should only be configurable for JWT tokens.

This feature is intended to support scenarios where an API is called by various clients that use different OAuth servers. A primary example is a single-tenant API that is consumed by a multi-tenant client.

A sample of the "API" change is this:

```python
_jwtOauth.configure_with_multiple_jwt_issuers(
    ["https://localhost:8443/oauth/%d/~" % i for i in range(1, 5)], 
    "back-end-api", 
    ["openid"])
```

**Comment by mtrojanowski** [comment]
This support has been added in version 1.1.0
